[2024-11-18T17:49:50.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:49:50.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-02T00:00:00+00:00 [queued]>
[2024-11-18T17:49:50.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-02T00:00:00+00:00 [queued]>
[2024-11-18T17:49:50.419+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-18T17:49:50.497+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2024-11-02 00:00:00+00:00
[2024-11-18T17:49:50.521+0000] {standard_task_runner.py:64} INFO - Started process 1677 to run task
[2024-11-18T17:49:50.544+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_job', 'scheduled__2024-11-02T00:00:00+00:00', '--job-id', '655', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpvgw6ymfq']
[2024-11-18T17:49:50.549+0000] {standard_task_runner.py:91} INFO - Job 655: Subtask spark_job
[2024-11-18T17:49:50.790+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_job scheduled__2024-11-02T00:00:00+00:00 [running]> on host 3fa30a842a1c
[2024-11-18T17:49:51.176+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-02T00:00:00+00:00'
[2024-11-18T17:49:51.185+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:49:51.255+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:49:51.259+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:50:46.333+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:46 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:50:46.355+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:46 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:50:46.357+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:46 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:50:22.450+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:50:58.305+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:50:59.084+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:51:02.234+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.237+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:51:02.240+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.273+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:51:02.702+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:51:02.733+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:51:02.735+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:51:03.857+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:51:03.880+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:51:03.903+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:51:03.906+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:51:03.909+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:51:06.893+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO Utils: Successfully started service 'sparkDriver' on port 36033.
[2024-11-18T17:51:07.356+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:51:07.723+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:51:07.751+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:51:07.755+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:51:07.797+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:51:07.917+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f012404e-f7c3-4b6f-9992-500f623208bf
[2024-11-18T17:51:08.021+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:51:08.157+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:51:16.468+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:16 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:51:18.006+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-11-18T17:51:18.016+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:18 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-11-18T17:51:18.104+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:18 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2024-11-18T17:51:20.494+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:22.598+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:22 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:22.602+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:22.604+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:22.608+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:22.610+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:22.614+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:22.615+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:22.616+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:22.617+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:22.620+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:22.621+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:22.623+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:22.624+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:22.625+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:22.626+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:22.626+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:22.627+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:22.628+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:22.628+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:22.629+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:22.634+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:22.640+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:22.642+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:22.651+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:22.659+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:22.667+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:22.678+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:22.681+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:22.682+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:22.712+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:22.716+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:22.719+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:22.723+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:22.732+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:22.736+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:22.738+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:40.551+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:40 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:40.564+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:40 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:40.565+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:40.565+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:40.566+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:40.566+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:40.566+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:40.567+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:40.567+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:40.567+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:40.568+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:40.569+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:40.572+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:40.573+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:40.574+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:40.575+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:40.576+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:40.580+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:40.582+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:40.584+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:40.585+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:40.586+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:40.588+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:40.594+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:40.596+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:40.598+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:40.601+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:40.602+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:40.603+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:40.603+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:40.604+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:40.605+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:40.606+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:40.606+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:40.606+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:40.607+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:40.607+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:52:00.710+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:00 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:52:03.139+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:03 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.8:7077 after 11 ms (0 ms spent in bootstraps)
[2024-11-18T17:52:04.308+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241118175204-0003
[2024-11-18T17:52:04.353+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 32929.
[2024-11-18T17:52:04.354+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO NettyBlockTransferService: Server created on 3fa30a842a1c:32929
[2024-11-18T17:52:04.372+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:52:04.472+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 3fa30a842a1c, 32929, None)
[2024-11-18T17:52:04.503+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMasterEndpoint: Registering block manager 3fa30a842a1c:32929 with 434.4 MiB RAM, BlockManagerId(driver, 3fa30a842a1c, 32929, None)
[2024-11-18T17:52:04.509+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 3fa30a842a1c, 32929, None)
[2024-11-18T17:52:04.513+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 3fa30a842a1c, 32929, None)
[2024-11-18T17:52:07.885+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:07 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:52:50.504+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:50 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@27412e6c)) by listener AppStatusListener took 1.069903105s.
[2024-11-18T17:52:54.633+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:53:28.292+0000] {spark_submit.py:634} INFO - 24/11/18 17:53:27 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@7bc5f37)) by listener AppStatusListener took 1.076637242s.
[2024-11-18T17:53:54.082+0000] {spark_submit.py:634} INFO - 24/11/18 17:53:53 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1b00eb6c)) by listener AppStatusListener took 1.113401256s.
[2024-11-18T17:54:10.450+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:09 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@76be3903)) by listener AppStatusListener took 1.514302897s.
[2024-11-18T17:54:21.555+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:33.166+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:33 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@21453565)) by listener AppStatusListener took 1.262619172s.
[2024-11-18T17:54:48.687+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:54:49.777+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: -9.
[2024-11-18T17:54:49.909+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=spark_job, run_id=scheduled__2024-11-02T00:00:00+00:00, execution_date=20241102T000000, start_date=20241118T174950, end_date=20241118T175449
[2024-11-18T17:54:50.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 655 for task spark_job (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: -9.; 1677)
[2024-11-18T17:54:50.239+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:54:50.518+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:54:50.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
