[2024-11-18T17:37:55.728+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:37:55.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_task scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-11-18T17:37:55.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_task scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-11-18T17:37:55.776+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-11-18T17:37:55.799+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-05-01 00:00:00+00:00
[2024-11-18T17:37:55.810+0000] {standard_task_runner.py:64} INFO - Started process 146 to run task
[2024-11-18T17:37:55.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_task', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '618', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmp7pu2s4co']
[2024-11-18T17:37:55.833+0000] {standard_task_runner.py:91} INFO - Job 618: Subtask spark_task
[2024-11-18T17:37:55.974+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_task scheduled__2024-05-01T00:00:00+00:00 [running]> on host 39153155bde1
[2024-11-18T17:37:56.238+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-11-18T17:37:56.245+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:37:56.270+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:37:56.275+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:38:31.004+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:30 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:38:31.019+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:38:31.021+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:38:31.249+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:38:31.628+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: ==============================================================
[2024-11-18T17:38:31.645+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:38:31.664+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: ==============================================================
[2024-11-18T17:38:31.677+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:38:31.916+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:38:31.961+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:38:32.008+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:38:32.863+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:38:32.889+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:38:32.924+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:38:32.930+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:38:32.941+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:38:36.730+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:36 INFO Utils: Successfully started service 'sparkDriver' on port 35933.
[2024-11-18T17:38:37.423+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:37 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:38:38.244+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:38 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:38:38.680+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:38:38.684+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:38:38.918+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:38 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:38:39.292+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:39 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0ce9ef6f-aa39-4c62-bf8f-2bbea35ed38c
[2024-11-18T17:38:39.568+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:39 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:38:39.790+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:39 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:38:50.708+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:50 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:38:54.274+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:54 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-11-18T17:38:54.286+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:54 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-11-18T17:38:54.302+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:54 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-11-18T17:38:54.570+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:54 INFO Utils: Successfully started service 'SparkUI' on port 4043.
[2024-11-18T17:39:04.040+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:04 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:39:14.769+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN TransportClientFactory: DNS resolution failed for spark/<unresolved>:7077 took 10177 ms
[2024-11-18T17:39:14.996+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:39:15.264+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:39:15.773+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:15 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:39:15.784+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:39:15.790+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:39:15.791+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:39:15.793+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:39:15.794+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:39:15.795+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:39:15.803+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:39:15.812+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:39:15.814+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:39:15.815+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:39:15.837+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:39:15.850+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:39:15.852+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/<unresolved>:7077
[2024-11-18T17:39:15.859+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:39:15.872+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:39:15.879+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:39:15.893+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:39:15.894+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:39:15.895+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:39:15.896+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:39:15.899+0000] {spark_submit.py:634} INFO - Caused by: java.net.UnknownHostException: spark
[2024-11-18T17:39:15.904+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
[2024-11-18T17:39:15.910+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2024-11-18T17:39:15.912+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2024-11-18T17:39:15.929+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2024-11-18T17:39:15.931+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2024-11-18T17:39:15.942+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2024-11-18T17:39:15.945+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2024-11-18T17:39:15.946+0000] {spark_submit.py:634} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2024-11-18T17:39:15.947+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2024-11-18T17:39:15.948+0000] {spark_submit.py:634} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2024-11-18T17:39:15.956+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2024-11-18T17:39:15.964+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2024-11-18T17:39:15.975+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2024-11-18T17:39:15.978+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2024-11-18T17:39:15.991+0000] {spark_submit.py:634} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2024-11-18T17:39:15.996+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2024-11-18T17:39:15.998+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2024-11-18T17:39:16.000+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2024-11-18T17:39:16.001+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2024-11-18T17:39:16.001+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2024-11-18T17:39:16.004+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2024-11-18T17:39:16.010+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2024-11-18T17:39:16.027+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2024-11-18T17:39:16.037+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2024-11-18T17:39:16.041+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2024-11-18T17:39:16.049+0000] {spark_submit.py:634} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2024-11-18T17:39:16.052+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2024-11-18T17:39:16.053+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2024-11-18T17:39:16.054+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2024-11-18T17:39:16.057+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2024-11-18T17:39:16.062+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2024-11-18T17:39:16.063+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2024-11-18T17:39:16.068+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2024-11-18T17:39:16.070+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2024-11-18T17:39:16.071+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:39:16.075+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:39:16.076+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:39:16.079+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:39:25.661+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:25 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:40:27.742+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:19 WARN TransportClientFactory: DNS resolution failed for spark/<unresolved>:7077 took 52831 ms
[2024-11-18T17:40:32.844+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:28 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:40:40.986+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:40 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-11-18T17:40:41.105+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:41 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-11-18T17:40:41.896+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:41 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38807.
[2024-11-18T17:40:41.910+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:41 INFO NettyBlockTransferService: Server created on 39153155bde1:38807
[2024-11-18T17:40:42.042+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:42 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:40:42.266+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:42 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 39153155bde1, 38807, None)
[2024-11-18T17:40:42.452+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:42 INFO BlockManagerMasterEndpoint: Registering block manager 39153155bde1:38807 with 434.4 MiB RAM, BlockManagerId(driver, 39153155bde1, 38807, None)
[2024-11-18T17:40:42.524+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:42 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 39153155bde1, 38807, None)
[2024-11-18T17:40:42.542+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:42 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 39153155bde1, 38807, None)
[2024-11-18T17:40:43.147+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:43 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:40:43.149+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:40:43.150+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:40:43.152+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:40:43.163+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:40:43.164+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:40:43.165+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:40:43.165+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:40:43.166+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:40:43.166+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:40:43.166+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:40:43.167+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:40:43.167+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:40:43.169+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/<unresolved>:7077
[2024-11-18T17:40:43.172+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:40:43.182+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:40:43.182+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:40:43.187+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:40:43.188+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:40:43.190+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:40:43.191+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:40:43.200+0000] {spark_submit.py:634} INFO - Caused by: java.net.UnknownHostException: spark: Temporary failure in name resolution
[2024-11-18T17:40:43.203+0000] {spark_submit.py:634} INFO - at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[2024-11-18T17:40:43.204+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
[2024-11-18T17:40:43.208+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
[2024-11-18T17:40:43.208+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
[2024-11-18T17:40:43.217+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2024-11-18T17:40:43.219+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2024-11-18T17:40:43.224+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2024-11-18T17:40:43.225+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2024-11-18T17:40:43.227+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2024-11-18T17:40:43.229+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2024-11-18T17:40:43.232+0000] {spark_submit.py:634} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2024-11-18T17:40:43.236+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2024-11-18T17:40:43.238+0000] {spark_submit.py:634} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2024-11-18T17:40:43.240+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2024-11-18T17:40:43.241+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2024-11-18T17:40:43.249+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2024-11-18T17:40:43.255+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2024-11-18T17:40:43.257+0000] {spark_submit.py:634} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2024-11-18T17:40:43.260+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2024-11-18T17:40:43.265+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2024-11-18T17:40:43.278+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2024-11-18T17:40:43.296+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2024-11-18T17:40:43.312+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2024-11-18T17:40:43.321+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2024-11-18T17:40:43.322+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2024-11-18T17:40:43.322+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2024-11-18T17:40:43.329+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2024-11-18T17:40:43.357+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2024-11-18T17:40:43.369+0000] {spark_submit.py:634} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2024-11-18T17:40:43.382+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2024-11-18T17:40:43.497+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2024-11-18T17:40:43.564+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2024-11-18T17:40:43.618+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2024-11-18T17:40:43.648+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2024-11-18T17:40:43.657+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2024-11-18T17:40:43.714+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2024-11-18T17:40:43.728+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2024-11-18T17:40:43.758+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:40:43.783+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:40:43.805+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:40:43.842+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:40:56.478+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:41:15.165+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:15 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener AppStatusListener took 1.303834269s.
[2024-11-18T17:41:17.539+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:17 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:42:00.633+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:42:22.459+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-18T17:42:22.646+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 INFO SparkUI: Stopped Spark web UI at http://39153155bde1:4043
[2024-11-18T17:42:22.712+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-18T17:42:22.741+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-18T17:42:22.783+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-11-18T17:42:22.958+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-18T17:42:23.684+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:23 INFO MemoryStore: MemoryStore cleared
[2024-11-18T17:42:23.701+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:23 INFO BlockManager: BlockManager stopped
[2024-11-18T17:42:23.723+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:23 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-18T17:42:23.738+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:23 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-18T17:42:24.111+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:24 INFO SparkContext: Successfully stopped SparkContext
[2024-11-18T17:42:32.591+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-18T17:42:32.650+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:32 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2024-11-18T17:42:32.947+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-18T17:42:32.951+0000] {spark_submit.py:634} INFO - File "/opt/***/dags/spark_job.py", line 14, in <module>
[2024-11-18T17:42:32.952+0000] {spark_submit.py:634} INFO - df = spark.createDataFrame(data, ["Name", "Application Type", "Use Count"])
[2024-11-18T17:42:32.953+0000] {spark_submit.py:634} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-18T17:42:32.954+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1443, in createDataFrame
[2024-11-18T17:42:32.954+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1485, in _create_dataframe
[2024-11-18T17:42:32.955+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1093, in _createFromLocal
[2024-11-18T17:42:32.957+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 952, in _inferSchemaFromList
[2024-11-18T17:42:32.957+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 624, in _jconf
[2024-11-18T17:42:32.958+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-18T17:42:32.959+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-18T17:42:32.959+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-18T17:42:32.960+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o23.sessionState.
[2024-11-18T17:42:32.960+0000] {spark_submit.py:634} INFO - : java.lang.IllegalStateException: LiveListenerBus is stopped.
[2024-11-18T17:42:32.960+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:92)
[2024-11-18T17:42:32.961+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:75)
[2024-11-18T17:42:32.961+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:115)
[2024-11-18T17:42:32.963+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
[2024-11-18T17:42:32.963+0000] {spark_submit.py:634} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-11-18T17:42:32.964+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
[2024-11-18T17:42:32.971+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
[2024-11-18T17:42:32.972+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
[2024-11-18T17:42:32.972+0000] {spark_submit.py:634} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-11-18T17:42:32.973+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
[2024-11-18T17:42:32.974+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
[2024-11-18T17:42:32.975+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-18T17:42:32.976+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-18T17:42:32.978+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-18T17:42:32.979+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-18T17:42:32.981+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-18T17:42:32.983+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-18T17:42:32.985+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-18T17:42:32.997+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-18T17:42:32.999+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-18T17:42:33.007+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-18T17:42:33.009+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-18T17:42:33.011+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:42:33.013+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:42:33.673+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Shutdown hook called
[2024-11-18T17:42:33.677+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-348ed390-72ef-45be-b8e0-e0139d08a67b
[2024-11-18T17:42:33.712+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-348ed390-72ef-45be-b8e0-e0139d08a67b/pyspark-4db657db-0c28-4e12-bb5f-40b2c504ceb8
[2024-11-18T17:42:33.747+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-c564bfef-fd6f-462d-b06e-4cd184871197
[2024-11-18T17:42:33.861+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:42:34.088+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.
[2024-11-18T17:42:34.140+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_dag, task_id=spark_task, run_id=scheduled__2024-05-01T00:00:00+00:00, execution_date=20240501T000000, start_date=20241118T173755, end_date=20241118T174234
[2024-11-18T17:42:34.247+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 618 for task spark_task (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.; 146)
[2024-11-18T17:42:34.325+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:42:34.368+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:42:34.376+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
